/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeRouteImport } from './routes/$code'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as BillTokenRouteImport } from './routes/bill.$token'
import { Route as GTokenRouteImport } from './routes/g.$token'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as GalleryCategoryRouteImport } from './routes/gallery.$category'
import { Route as InvoiceTokenRouteImport } from './routes/invoice.$token'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img.$'
import { Route as ApiPublicCrmGalleryCoverTokenRouteImport } from './routes/api/public/crm/gallery-cover.$token'
import { Route as ApiPublicCrmGalleryOgTokenRouteImport } from './routes/api/public/crm/gallery-og.$token'
import { Route as ApiPublicCrmImgSplatRouteImport } from './routes/api/public/crm/img.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BillTokenRoute = BillTokenRouteImport.update({
  id: '/bill/$token',
  path: '/bill/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GTokenRoute = GTokenRouteImport.update({
  id: '/g/$token',
  path: '/g/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryCategoryRoute = GalleryCategoryRouteImport.update({
  id: '/gallery/$category',
  path: '/gallery/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceTokenRoute = InvoiceTokenRouteImport.update({
  id: '/invoice/$token',
  path: '/invoice/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmGalleryCoverTokenRoute =
  ApiPublicCrmGalleryCoverTokenRouteImport.update({
    id: '/api/public/crm/gallery-cover/$token',
    path: '/api/public/crm/gallery-cover/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCrmGalleryOgTokenRoute =
  ApiPublicCrmGalleryOgTokenRouteImport.update({
    id: '/api/public/crm/gallery-og/$token',
    path: '/api/public/crm/gallery-og/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCrmImgSplatRoute = ApiPublicCrmImgSplatRouteImport.update({
  id: '/api/public/crm/img/$',
  path: '/api/public/crm/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/bill/$token': typeof BillTokenRoute
  '/g/$token': typeof GTokenRoute
  '/gallery/$category': typeof GalleryCategoryRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/gallery/': typeof GalleryIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/crm/gallery-cover/$token': typeof ApiPublicCrmGalleryCoverTokenRoute
  '/api/public/crm/gallery-og/$token': typeof ApiPublicCrmGalleryOgTokenRoute
  '/api/public/crm/img/$': typeof ApiPublicCrmImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/bill/$token': typeof BillTokenRoute
  '/g/$token': typeof GTokenRoute
  '/gallery/$category': typeof GalleryCategoryRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/gallery': typeof GalleryIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/crm/gallery-cover/$token': typeof ApiPublicCrmGalleryCoverTokenRoute
  '/api/public/crm/gallery-og/$token': typeof ApiPublicCrmGalleryOgTokenRoute
  '/api/public/crm/img/$': typeof ApiPublicCrmImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$code': typeof CodeRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/bill/$token': typeof BillTokenRoute
  '/g/$token': typeof GTokenRoute
  '/gallery/$category': typeof GalleryCategoryRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/gallery/': typeof GalleryIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/crm/gallery-cover/$token': typeof ApiPublicCrmGalleryCoverTokenRoute
  '/api/public/crm/gallery-og/$token': typeof ApiPublicCrmGalleryOgTokenRoute
  '/api/public/crm/img/$': typeof ApiPublicCrmImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$code'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/review'
    | '/services'
    | '/sitemap.xml'
    | '/admin'
    | '/crm'
    | '/bill/$token'
    | '/g/$token'
    | '/gallery/$category'
    | '/invoice/$token'
    | '/sign/$token'
    | '/gallery/'
    | '/api/public/google/callback'
    | '/api/public/img/$'
    | '/api/public/crm/gallery-cover/$token'
    | '/api/public/crm/gallery-og/$token'
    | '/api/public/crm/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$code'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/review'
    | '/services'
    | '/sitemap.xml'
    | '/admin'
    | '/crm'
    | '/bill/$token'
    | '/g/$token'
    | '/gallery/$category'
    | '/invoice/$token'
    | '/sign/$token'
    | '/gallery'
    | '/api/public/google/callback'
    | '/api/public/img/$'
    | '/api/public/crm/gallery-cover/$token'
    | '/api/public/crm/gallery-og/$token'
    | '/api/public/crm/img/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$code'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/review'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/crm'
    | '/bill/$token'
    | '/g/$token'
    | '/gallery/$category'
    | '/invoice/$token'
    | '/sign/$token'
    | '/gallery/'
    | '/api/public/google/callback'
    | '/api/public/img/$'
    | '/api/public/crm/gallery-cover/$token'
    | '/api/public/crm/gallery-og/$token'
    | '/api/public/crm/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CodeRoute: typeof CodeRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BillTokenRoute: typeof BillTokenRoute
  GTokenRoute: typeof GTokenRoute
  GalleryCategoryRoute: typeof GalleryCategoryRoute
  InvoiceTokenRoute: typeof InvoiceTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
  ApiPublicCrmGalleryCoverTokenRoute: typeof ApiPublicCrmGalleryCoverTokenRoute
  ApiPublicCrmGalleryOgTokenRoute: typeof ApiPublicCrmGalleryOgTokenRoute
  ApiPublicCrmImgSplatRoute: typeof ApiPublicCrmImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$code': {
      id: '/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/bill/$token': {
      id: '/bill/$token'
      path: '/bill/$token'
      fullPath: '/bill/$token'
      preLoaderRoute: typeof BillTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$token': {
      id: '/g/$token'
      path: '/g/$token'
      fullPath: '/g/$token'
      preLoaderRoute: typeof GTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$category': {
      id: '/gallery/$category'
      path: '/gallery/$category'
      fullPath: '/gallery/$category'
      preLoaderRoute: typeof GalleryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$token': {
      id: '/invoice/$token'
      path: '/invoice/$token'
      fullPath: '/invoice/$token'
      preLoaderRoute: typeof InvoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/gallery-cover/$token': {
      id: '/api/public/crm/gallery-cover/$token'
      path: '/api/public/crm/gallery-cover/$token'
      fullPath: '/api/public/crm/gallery-cover/$token'
      preLoaderRoute: typeof ApiPublicCrmGalleryCoverTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/gallery-og/$token': {
      id: '/api/public/crm/gallery-og/$token'
      path: '/api/public/crm/gallery-og/$token'
      fullPath: '/api/public/crm/gallery-og/$token'
      preLoaderRoute: typeof ApiPublicCrmGalleryOgTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/img/$': {
      id: '/api/public/crm/img/$'
      path: '/api/public/crm/img/$'
      fullPath: '/api/public/crm/img/$'
      preLoaderRoute: typeof ApiPublicCrmImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CodeRoute: CodeRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BillTokenRoute: BillTokenRoute,
  GTokenRoute: GTokenRoute,
  GalleryCategoryRoute: GalleryCategoryRoute,
  InvoiceTokenRoute: InvoiceTokenRoute,
  SignTokenRoute: SignTokenRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
  ApiPublicCrmGalleryCoverTokenRoute: ApiPublicCrmGalleryCoverTokenRoute,
  ApiPublicCrmGalleryOgTokenRoute: ApiPublicCrmGalleryOgTokenRoute,
  ApiPublicCrmImgSplatRoute: ApiPublicCrmImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
