REVOKE EXECUTE ON FUNCTION public.apply_row(text, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.content_snapshot(text[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.delete_row(text, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_content_change() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pk_where_clause(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_view_duration(uuid, integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.resolve_share_link(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.restore_snapshot(jsonb, text[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.share_link_og_image(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.timeline_goto(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.timeline_state() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_row(text, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.content_snapshot(text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.delete_row(text, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.pk_where_clause(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.record_view_duration(uuid, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.resolve_share_link(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.restore_snapshot(jsonb, text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.share_link_og_image(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.timeline_goto(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.timeline_state() TO service_role;